my_dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"        # Use 'PROJECT_ID' for the project ID
      dataset: "{{ env_var('DATASET_ID') }}"        # Use 'DATASET_ID' for the dataset ID
      keyfile: "{{ env_var('BIGQUERY_KEYFILE') }}"  # Use 'BIGQUERY_KEYFILE' for the path to the keyfile
      threads: 4
      timeout_seconds: 300
      location: US